language: python

matrix:
    include:
        - os: linux
        - os: osx
          language: generic

install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - source $HOME/miniconda/bin/activate
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda activate earth-analytics-python
  - python -c "import earthpy"
  - conda list
